BookStoreOnline/Areas/Admin/Controllers/OrdersAdminController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BookStoreOnline.Models;
using static BookStoreOnline.Areas.Admin.Constants.Constants;

namespace BookStoreOnline.Areas.Admin.Controllers
{
    public class OrdersAdminController : Controller
    {
        private NhaSachEntities db = new NhaSachEntities();

        // GET: Admin/Orders
        public ActionResult Index(string status)
        {
            List<DONHANG> donHang;

            if (!string.IsNullOrEmpty(status))
            {
                if (Enum.TryParse(status, out StatusOrder parsedStatusOrder))
                {
                    switch (parsedStatusOrder)
                    {
                        case StatusOrder.NoInform:
                            donHang = db.DONHANGs.Where(x => x.TrangThai == StatusOrder.NoInform.ToString()).ToList();
                            break;
                        case StatusOrder.Informed:
                            donHang = db.DONHANGs.Where(x => x.TrangThai == StatusOrder.Informed.ToString()).ToList();
                            break;
                        case StatusOrder.Shipping:
                            donHang = db.DONHANGs.Where(x => x.TrangThai == StatusOrder.Shipping.ToString()).ToList();
                            break;
                        case StatusOrder.Received:
                            donHang = db.DONHANGs.Where(x => x.TrangThai == StatusOrder.Received.ToString()).ToList();
                            break;
                        case StatusOrder.Canceled:
                            donHang = db.DONHANGs.Where(x => x.TrangThai == StatusOrder.Canceled.ToString()).ToList();
                            break;
                        default:
                            donHang = db.DONHANGs.ToList();
                            break;
                    }
                }
                else
                {
                    donHang = db.DONHANGs.ToList();
                }
            }
            else
            {
                // If no status is provided, return all orders
                donHang = db.DONHANGs.ToList();
            }
            return View(donHang.ToList());
        }

        // GET: Admin/Orders/Details/5
        public ActionResult Details(int id)
        {
            var detail = db.CHITIETDONHANGs.Where(d => d.MaDonHang == id).ToList();
            ViewBag.Detail = detail;
            var order = db.DONHANGs.FirstOrDefault(d => d.MaDonHang == id);
            ViewBag.Total = order.TongTien;
            return View(order);
        }

        // GET: Admin/Orders/Create
        public ActionResult Create()
        {
            ViewBag.IDCus = new SelectList(db.KHACHHANGs, "ID", "Ten");
            return View();
        }

        // POST: Admin/Orders/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaDonHang,DiaChi,TrangThai,NgayDat,ID")] DONHANG donHang)
        {
            if (ModelState.IsValid)
            {
                db.DONHANGs.Add(donHang);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.IDCus = new SelectList(db.KHACHHANGs, "ID", "Ten", donHang.ID);
            return View(donHang);
        }

        // GET: Admin/Orders/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DONHANG donHang = db.DONHANGs.Find(id);
            if (donHang == null)
            {
                return HttpNotFound();
            }
            ViewBag.IDCus = new SelectList(db.KHACHHANGs, "ID", "Ten", donHang.ID);
            return View(donHang);
        }

        // POST: Admin/Orders/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaDonHang,DiaChi,TrangThai,NgayDat,ID")] DONHANG donHang)
        {
            if (ModelState.IsValid)
            {
                db.Entry(donHang).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.IDCus = new SelectList(db.KHACHHANGs, "ID", "Ten ", donHang.ID);
            return View(donHang);
        }

        // GET: Admin/Orders/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DONHANG donHang = db.DONHANGs.Find(id);
            if (donHang == null)
            {
                return HttpNotFound();
            }
            return View(donHang);
        }

        // POST: Admin/Orders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            DONHANG donHang = db.DONHANGs.Find(id);
            db.DONHANGs.Remove(donHang);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public ActionResult ConfirmOrder(int id)
        {
            var order = db.DONHANGs.FirstOrDefault(item => item.MaDonHang == id);
            order.TrangThai = StatusOrder.Informed.ToString();
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult CancelOrder(int id)
        {
            var order = db.DONHANGs.FirstOrDefault(item => item.MaDonHang == id);
            order.TrangThai = StatusOrder.Canceled.ToString();
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Shipping(int id)
        {
            var order = db.DONHANGs.FirstOrDefault(item => item.MaDonHang == id);
            order.TrangThai = StatusOrder.Shipping.ToString();
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult ShippingSuccess(int id)
        {
            var order = db.DONHANGs.FirstOrDefault(item => item.MaDonHang == id);
            order.TrangThai = StatusOrder.Received.ToString();
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

BookStoreOnline/Areas/Admin/Views/OrdersAdmin/Details.cshtml
@model BookStoreOnline.Models.DONHANG
@using BookStoreOnline.Areas.Admin.Constants;
@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
    var price = System.Globalization.CultureInfo.GetCultureInfo("vi-VN");

}
<div class="card-body">
    <h2>Chi tiết đơn hàng</h2>
</div>
<div class="card-body">
    <div class="table-responsive">
        <table class="table table-striped text-center">
            <tr>
                <th>Sản phẩm</th>
                <th>Tên sản phẩm</th>
                <th>Số lượng</th>
                <th>Đơn giá</th>
            </tr>

            @foreach (var item in ViewBag.Detail)
            {
                <tr>
                    <td style="width: 15%;">
                        <img src="~/Images/@item.SANPHAM.Anh" style="width: 60%; position: relative; left: 0;height:100px" />
                    </td>
                    <td style="width:35%">
                        @item.SANPHAM.TenSanPham
                    </td>
                    <td>
                        @item.SoLuong
                    </td>
                    <td>
                        <h6>@String.Format(price, "{0:c0}", item.SANPHAM.Gia)</h6>
                    </td>
                </tr>
            }

        </table>

        @*<hr />*@
        <div class="container-fluid">

            <!-- Page Heading -->
            <div class="row">
                <div class="row">
                    <div class="col-lg-6">
                    </div>
                    <div class="col-lg-6">
                        <div class="card shadow mb-4">
                            <!-- Card Header - Dropdown -->
                            <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                                <h6 class="m-0 font-weight-bold text-primary">Chi tiết tổng đơn</h6>

                            </div>
                            <!-- Card Body -->
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-6">
                                        Tên khách hàng: <span style="font-weight:bold">@Model.KHACHHANG.Ten</span> <br /><br />

                                        Địa chỉ giao hàng: @Model.DiaChi <br /> <br />
                                        @if (Model.TrangThai == Constants.StatusOrder.NoInform.ToString())
                                        {
                                            <a href="@Url.Action("ConfirmOrder/"+ Model.MaDonHang,"OrdersAdmin")" class="btn btn-success">Xác nhận đơn hàng</a>
                                        }
                                        @if (Model.TrangThai == Constants.StatusOrder.Informed.ToString())
                                        {
                                            <a href="@Url.Action("Shipping/"+ Model.MaDonHang,"OrdersAdmin")" class="btn btn-success">Chuyển cho shipper</a>
                                        }
                                        @if (Model.TrangThai == Constants.StatusOrder.Shipping.ToString())
                                        {
                                            <a href="@Url.Action("ShippingSuccess/"+ Model.MaDonHang,"OrdersAdmin")" class="btn btn-success">Xác nhận giao thành công</a>
                                        }
                                        @if (Model.TrangThai != Constants.StatusOrder.Canceled.ToString() && Model.TrangThai != Constants.StatusOrder.Received.ToString())
                                        {
                                            <a href="@Url.Action("CancelOrder/"+ Model.MaDonHang,"OrdersAdmin")" class="btn btn-danger">Hủy đơn hàng</a>
                                        }
                                    </div>
                                    <div class="col-6">
                                        <div class="card-body">
                                            <div class="row no-gutters align-items-center">
                                                <div class="col mr-2">
                                                    <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                                        Tổng tiền
                                                    </div>
                                                    <div class="h5 mb-0 font-weight-bold text-gray-800"> @String.Format(price, "{0:c0}", ViewBag.Total)</div>
                                                </div>
                                                <div class="col-auto d-flex align-items-center">
                                                    <i class="fas fa-calendar fa-2x text-gray-300 me-2"></i>
                                                    <span class="text-muted">@Model.TrangThai</span>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
<p>

    @Html.ActionLink("Quay lại", "Index", null, new { @class = "btn btn-secondary", style = "color: white !important;" })
</p>

BookStoreOnline/Areas/Admin/Views/OrdersAdmin/Index.cshtml
@model IEnumerable<BookStoreOnline.Models.DONHANG>
@using BookStoreOnline.Areas.Admin.Constants;

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="card-body">
    <h2>Danh sách đơn hàng</h2>
</div>
<div class="card-body">
    <div class="table-responsive">
        <table class="table table-striped text-center">
            <tr>
                <th>Khách hàng</th>
                <th>Ngày đặt</th>
                <th>Địa chỉ giao hàng</th>
                <th>Trạng thái đơn hàng</th>
                <th>Phương Thức Thanh Toán</th>
                <th>Trạng Thái Thanh Toán</th>
                <th>Hoạt động</th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.KHACHHANG.Ten</td>
                    <td>@String.Format("{0:dd/MM/yyyy}", item.NgayDat)</td>
                    <td>@item.DiaChi</td>
                    @* Chuyển đổi từ value ENUM sang Description *@
                    @{
                        var trangThaiDonHangEnum = (Constants.StatusOrder)Enum.Parse(typeof(Constants.StatusOrder), item.TrangThai);
                        var trangThai = @EHelper.GetEnumDescription((Constants.StatusOrder)trangThaiDonHangEnum);

                        var trangThaiThanhToanEnum = (Constants.StatusPayment)Enum.Parse(typeof(Constants.StatusPayment), item.TrangThaiThanhToan);
                        var trangThaiThanhToan = @EHelper.GetEnumDescription((Constants.StatusPayment)trangThaiThanhToanEnum);
                        
                        var phuongThucThanhToanEnum = (Constants.TypePayment)Enum.Parse(typeof(Constants.TypePayment), item.PhuongThucThanhToan);
                        var phuongThucThanhToan = @EHelper.GetEnumDescription((Constants.TypePayment)phuongThucThanhToanEnum);
                    }
                    <td>@trangThai</td>
                    <td>@trangThaiThanhToan</td>
                    <td>@phuongThucThanhToan</td>
                    <td>
                        <a href="@Url.Action("Details/"+item.MaDonHang,"OrdersAdmin")" class="btn btn-info">Xem chi tiết</a>
                    </td>
                </tr>
            }


        </table>

    </div>
</div>
@*@if (item.StatusOrder == 0)
    {
        <td style="color:red">Chưa xác nhận</td>
    }
    else
    {
        <td style="color:forestgreen">Đã xác nhận</td>
    }*@