BookStoreOnline/Areas/Admin/Controllers/AdminAccountsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BookStoreOnline.Areas.Admin.Constants;
using BookStoreOnline.Core;
using BookStoreOnline.Models;
using static BookStoreOnline.Areas.Admin.Constants.Constants;

namespace BookStoreOnline.Areas.Admin.Controllers
{
    public class AdminAccountsController : Controller
    {
        private NhaSachEntities db = new NhaSachEntities();

        // GET: Admin/NHANVIENs.
        public ActionResult Index()
        {
            return View(db.NHANVIENs.ToList());
        }

        // GET: Admin/NHANVIENs.Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NHANVIEN nhanVien = db.NHANVIENs.Find(id);
            if (nhanVien == null)
            {
                return HttpNotFound();
            }
            return View(nhanVien);
        }

        // GET: Admin/NHANVIENs.Create
        public ActionResult Create()
        {
            var roles = from AdminRole e in Enum.GetValues(typeof(AdminRole))
                        select new { Value = e.ToString(), Text = e.GetDescription() };

            ViewBag.Quyen = new SelectList(roles, "Value", "Text");
            return View();
        }

        // POST: Admin/NHANVIENs.Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Ten,Email,Quyen")] NHANVIEN nhanVienMoi)
        {
            if (ModelState.IsValid)
            {
                nhanVienMoi.MatKhau = Extension.GetMd5Hash("123456789");
                nhanVienMoi.NgayTao = DateTime.Now;
                nhanVienMoi.TrangThai = true;
                db.NHANVIENs.Add(nhanVienMoi);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(nhanVienMoi);
        }

        // GET: Admin/NHANVIENs.Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NHANVIEN nhanVien = db.NHANVIENs.Find(id);
            if (nhanVien == null)
            {
                return HttpNotFound();
            }
            var roles = from AdminRole e in Enum.GetValues(typeof(AdminRole))
                        select new { Value = e.ToString(), Text = e.GetDescription() };

            ViewBag.Quyen = new SelectList(roles, "Value", "Text");
            return View(nhanVien);
        }

        // POST: Admin/NHANVIENs.Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaNV,Ten,Email,Quyen")] NHANVIEN nhanVien)
        {
            if (ModelState.IsValid)
            {
                NHANVIEN admAccount = db.NHANVIENs.Find(nhanVien.MaNV);
                admAccount.Ten = nhanVien.Ten;
                admAccount.Quyen = nhanVien.Quyen;
                admAccount.Email = nhanVien.Email;
                db.Entry(admAccount).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(nhanVien);
        }

        // GET: Admin/NHANVIENs.Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NHANVIEN nhanVien = db.NHANVIENs.Find(id);
            if (nhanVien == null)
            {
                return HttpNotFound();
            }
            return View(nhanVien);
        }

        // POST: Admin/NHANVIENs.Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            NHANVIEN nhanVien = db.NHANVIENs.Find(id);
            db.NHANVIENs.Remove(nhanVien);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }


        public ActionResult DisableAccount(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NHANVIEN nhanVien = db.NHANVIENs.Find(id);
            if (nhanVien == null)
            {
                return HttpNotFound();
            }
            return View(nhanVien);
        }

        [HttpPost, ActionName("DisableAccount")]
        [ValidateAntiForgeryToken]
        public ActionResult DisableAccountConfirmed(int id)
        {
            NHANVIEN nhanVien = db.NHANVIENs.Find(id);
            if (nhanVien == null)
            {
                return HttpNotFound();
            }

            nhanVien.TrangThai = false; // Assuming there is a property 'IsActive' in the AdminAccount model to indicate if the account is active or not
            db.SaveChanges();

            return RedirectToAction("Index");
        }


        public ActionResult EnableAccount(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NHANVIEN nhanVien = db.NHANVIENs.Find(id);
            if (nhanVien == null)
            {
                return HttpNotFound();
            }
            return View(nhanVien);
        }

        [HttpPost, ActionName("EnableAccount")]
        [ValidateAntiForgeryToken]
        public ActionResult EnableAccountAccountConfirmed(int id)
        {
            NHANVIEN nhanVien = db.NHANVIENs.Find(id);
            if (nhanVien == null)
            {
                return HttpNotFound();
            }

            nhanVien.TrangThai = true; // Assuming there is a property 'IsActive' in the AdminAccount model to indicate if the account is active or not
            db.SaveChanges();

            return RedirectToAction("Index");
        }

    }
}

BookStoreOnline/Areas/Admin/Views/AdminAccounts/Create.cshtml
@model BookStoreOnline.Models.NHANVIEN

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="card-body">
    <h2>Thêm người quản trị mới</h2>
</div>
@using (Html.BeginForm(("Create", "AdminAccounts", FormMethod.Post, new { @enctype = "multipart/form-data" })))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="mb-3">
            <label for="Name" class="form-label"> Tên người quản trị</label>
            @Html.EditorFor(model => model.Ten, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Ten, "", new { @class = "text-danger" })
        </div>

        <div class="mb-3">
            <label for="Email" class="form-label">  Email</label>
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label for="DisplayPassword" class="form-label">Mật khẩu sau khi tạo tài khoản</label>
        <input type="text" class="form-control" value="123456789" readonly="readonly" />
    </div>
    <div class="mb-3">
        <label for="Role" class="form-label">Quyền hạn</label> 
        @Html.DropDownListFor(model => model.Quyen, (SelectList)ViewBag.Quyen, "Chọn quyền hạn", new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.Quyen, "", new { @class = "text-danger" })
    </div>


    <div class="d-flex justify-content-between align-items-center">
        @Html.ActionLink("Quay lại", "Index", null, new { @class = "btn btn-secondary", style = "color: white !important;" })
        <button type="submit" class="btn btn-primary" style="color: white !important;">Thêm</button>
    </div>

}

BookStoreOnline/Areas/Admin/Views/AdminAccounts/Delete.cshtml
@model BookStoreOnline.Models.NHANVIEN
@using BookStoreOnline.Areas.Admin.Constants;
@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="card-body">
    <h2 class="card-title">Xóa</h2>
</div>
<div class="card mt-4 shadow-sm">
    <div class="card-body">
        <h3 class="text-center mb-4">Bạn có chắc chắn muốn xóa danh mục này?</h3>
        <h4 class="text-center">
            @*@EnumExtensions.GetDescription(Model.AdminRole)*@

            Người dùng: @Html.DisplayFor(model => model.Ten)
        </h4>
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            <div class="d-flex justify-content-between">
                <input type="submit" value="Xóa" class="btn btn-danger" />
                @Html.ActionLink("Quay lại", "Index", null, new { @class = "btn btn-secondary", style = "color: white !important;" })
            </div>
        }
    </div>
</div>

BookStoreOnline/Areas/Admin/Views/AdminAccounts/Details.cshtml
@model BookStoreOnline.Models.NHANVIEN
@using BookStoreOnline.Areas.Admin.Constants;
@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
<div class="card-body">
    <h2>Tài khoản quản trị</h2>

    <div>
        <h4>AdminAccount</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Ten)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Email)
            </dd>

            <dt>
                @*<td>@EnumExtensions.GetDescription((Constants.StatusOrder)item.AdminRole)</td>
            </dt>*@

            <dd>
                @Html.DisplayFor(model => model.TrangThai)
            </dd>



        </dl>
    </div>
    <p>

        @Html.ActionLink("Quay lại", "Index", null, new { @class = "btn btn-secondary", style = "color: white !important;" })
    </p>
</div>

BookStoreOnline/Areas/Admin/Views/AdminAccounts/DisableAccount.cshtml
@model BookStoreOnline.Models.NHANVIEN
@{
    ViewBag.Title = "DisableAccount";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="card-body">
    <h2 class="card-title">Vô hiệu khóa</h2>
</div>
<div class="card mt-4 shadow-sm">
    <div class="card-body">
        <h3 class="text-center mb-4">Bạn có chắc chắn muốn vô hiệu khóa Người dùng này?</h3>
        <h4 class="text-center">
            Người dùng: @Html.DisplayFor(model => model.Ten)
        </h4>
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            <div class="d-flex justify-content-between">
                <input type="submit" value="Vô hiệu" class="btn btn-danger" />
                @Html.ActionLink("Quay lại", "Index", null, new { @class = "btn btn-secondary", style = "color: white !important;" })
            </div>
        }
    </div>
</div>

BookStoreOnline/Areas/Admin/Views/AdminAccounts/Edit.cshtml
@model BookStoreOnline.Models.NHANVIEN

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
<div class="card-body">
    <h2>Chỉnh sửa tài khoản quản trị</h2>

    @using (Html.BeginForm("Edit", "AdminAccounts", FormMethod.Post, new { @enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">

            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.MaNV)



            <div class="mb-3">
                <label for="CategoryName" class="form-label"> Tên người quản trị</label>
                @Html.EditorFor(model => model.Ten, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ten)
            </div>


            <div class="mb-3">
                <label for="CategoryName" class="form-label"> Email</label>
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email)
            </div>

            <div class="mb-3">
                <label for="Quyen" class="form-label">Quyền hạn</label>
                <select id="Quyen" name="Quyen" class="form-control">
                    @foreach (var role in ViewBag.Quyen)
                    {
                        <option value="@role.Value" @(Model.Quyen.ToString() == role.Value ? "selected" : "")>@role.Text</option>
                    }
                </select>
                @Html.ValidationMessageFor(model => model.Quyen, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="d-flex justify-content-between align-items-center">
            @Html.ActionLink("Quay lại", "Index", null, new { @class = "btn btn-secondary", style = "color: white !important;" })
            <button type="submit" class="btn btn-primary">Lưu</button>
        </div>

    }
</div>

BookStoreOnline/Areas/Admin/Views/AdminAccounts/EnableAccount.cshtml
@model BookStoreOnline.Models.NHANVIEN
@{
    ViewBag.Title = "EnableAccount";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="card-body">
    <h2 class="card-title">Vô hiệu khóa</h2>
</div>
<div class="card mt-4 shadow-sm">
    <div class="card-body">
        <h3 class="text-center mb-4">Bạn có chắc chắn muốn kích hoạt Người dùng này?</h3>
        <h4 class="text-center">
            Người dùng: @Html.DisplayFor(model => model.Ten)
        </h4>
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            <div class="d-flex justify-content-between">
                <input type="submit" value="Kích hoạt" class="btn btn-danger" />
                @Html.ActionLink("Quay lại", "Index", null, new { @class = "btn btn-secondary", style = "color: white !important;" })
            </div>
        }
    </div>
</div>

BookStoreOnline/Areas/Admin/Views/AdminAccounts/Index.cshtml
@model IEnumerable<BookStoreOnline.Models.NHANVIEN>
@using BookStoreOnline.Areas.Admin.Constants;

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}



<div class="card-body">
    <h2>Danh sách tài khoản quản trị</h2>
</div>
<div class="text-right">
    <button type="button" class="btn btn-primary" onclick="location.href='/Admin/AdminAccounts/Create';">Thêm người quản trị</button>
</div>
<table class="table table-bordered">
    <tr>
        <th>
            STT
        </th>
        <th>
            Tên người dùng
        </th>
        <th>
            Email
        </th>
        <th>
            Quyền hạn
        </th>

        <th>Thời gian tạo</th>
    </tr>
    @{
        int STT = 1; // Initialize the counter
    }
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @STT
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ten)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @{
                    var role = (Constants.AdminRole)Enum.Parse(typeof(Constants.AdminRole), item.Quyen);
                    var description = @EHelper.GetEnumDescription((Constants.AdminRole)role);
                }
                @description
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NgayTao)
            </td>

            <td>
                <div class="col">

                    <a href="@Url.Action("Edit", new { id = item.MaNV })" class="btn btn-sm btn-warning">Chỉnh sửa</a>

                    @if (item.TrangThai == true)
                    {
                        <a href="@Url.Action("DisableAccount", new { id = item.MaNV })" class="btn btn-sm btn-success">Vô hiệu hóa</a>
                    }
                    else
                    {
                        <a href="@Url.Action("EnableAccount", new { id = item.MaNV })" class="btn btn-sm btn-danger">Kích hoạt</a>
                    }
                </div>

            </td>
        </tr>

        STT++;
    }


</table>