BookStoreOnline/Areas/Admin/Controllers/PromotionController.cs
using BookStoreOnline.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace BookStoreOnline.Areas.Admin.Controllers
{
    public class PromotionController : Controller
    {
        private NhaSachEntities db = new NhaSachEntities();

        // GET: Admin/Promotion
        public ActionResult Index()
        {
            return View(db.KHUYENMAIs.ToList());
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,TenChuongTrinh,MaKM,MoTa,NgayTao,NgayBatDau,NgayKetThuc,SoTienKM,SoTienMuaHangToiThieu,SoLanDung,KichHoat")] KHUYENMAI khuyenMai)
        {
            if (ModelState.IsValid)
            {
                db.KHUYENMAIs.Add(khuyenMai);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(khuyenMai);
        }


        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            KHUYENMAI khuyenMai = db.KHUYENMAIs.Find(id);
            if (khuyenMai == null)
            {
                return HttpNotFound();
            }
            return View(khuyenMai);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            KHUYENMAI khuyenMai = db.KHUYENMAIs.Find(id);
            db.KHUYENMAIs.Remove(khuyenMai);
            db.SaveChanges();
            return RedirectToAction("Index");
        }


        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            KHUYENMAI khuyenMai = db.KHUYENMAIs.Find(id);
            if (khuyenMai == null)
            {
                return HttpNotFound();
            }

            return View(khuyenMai);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,TenChuongTrinh,MaKM,MoTa,NgayTao,NgayBatDau,NgayKetThuc,SoTienKM,SoTienMuaHangToiThieu,SoLanDung,KichHoat")] KHUYENMAI khuyenMai)
        {
            if (ModelState.IsValid)
            {
                db.Entry(khuyenMai).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(khuyenMai);
        }


    }
}

BookStoreOnline/Areas/Admin/Views/Promotion/Create.cshtml
@model BookStoreOnline.Models.KHUYENMAI

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="card-body">
    <h2>Thêm mã giảm giá mới</h2>
</div>
@using (Html.BeginForm("Create", "Promotion", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="mb-3">
            <label for="TenChuongTrinh" class="form-label">Tên chương trình</label>
            @Html.EditorFor(model => model.TenChuongTrinh, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TenChuongTrinh, "", new { @class = "text-danger" })
        </div>

        <div class="mb-3">
            <label for="MaKM" class="form-label">Mã khuyến mãi</label>
            @Html.EditorFor(model => model.MaKM, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.MaKM, "", new { @class = "text-danger" })
        </div>

        <div class="mb-3">
            <label for="MoTa" class="form-label">Mô tả</label>
            @Html.EditorFor(model => model.MoTa, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.MoTa, "", new { @class = "text-danger" })
        </div>

        <div class="mb-3">
            <label for="NgayTao" class="form-label">Ngày tạo</label>
            @Html.EditorFor(model => model.NgayTao, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.NgayTao, "", new { @class = "text-danger" })
        </div>

        <div class="mb-3">
            <label for="NgayBatDau" class="form-label">Ngày bắt đầu</label>
            @Html.EditorFor(model => model.NgayBatDau, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.NgayBatDau, "", new { @class = "text-danger" })
        </div>

        <div class="mb-3">
            <label for="NgayKetThuc" class="form-label">Ngày kết thúc</label>
            @Html.EditorFor(model => model.NgayKetThuc, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.NgayKetThuc, "", new { @class = "text-danger" })
        </div>

        <div class="mb-3">
            <label for="SoTienKM" class="form-label">Số tiền khuyến mãi</label>
            @Html.EditorFor(model => model.SoTienKM, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.SoTienKM, "", new { @class = "text-danger" })
        </div>

        <div class="mb-3">
            <label for="SoTienMuaHangToiThieu" class="form-label">Số tiền mua hàng tối thiểu</label>
            @Html.EditorFor(model => model.SoTienMuaHangToiThieu, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.SoTienMuaHangToiThieu, "", new { @class = "text-danger" })
        </div>

        <div class="mb-3">
            <label for="SoLanDung" class="form-label">Số lần dùng</label>
            @Html.EditorFor(model => model.SoLanDung, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.SoLanDung, "", new { @class = "text-danger" })
        </div>

        <div class="mb-3">
            <label for="KichHoat" class="form-label">Kích hoạt</label>
            <div class="form-check">
                @Html.EditorFor(model => model.KichHoat, new { htmlAttributes = new { @class = "form-check-input" } })
                @Html.ValidationMessageFor(model => model.KichHoat, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="d-flex justify-content-between align-items-center">
            @Html.ActionLink("Quay lại", "Index", null, new { @class = "btn btn-secondary", style = "color: white !important;" })
            <button type="submit" class="btn btn-primary" style="color: white !important;">Thêm</button>
        </div>
    </div>
}

BookStoreOnline/Areas/Admin/Views/Promotion/Delete.cshtml
@model BookStoreOnline.Models.KHUYENMAI

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="card-body">
    <h2 class="card-title">Xóa</h2>
</div>
<div class="card mt-4 shadow-sm">
    <div class="card-body">
        <h3 class="text-center mb-4">Bạn có chắc chắn muốn xóa mã khuyến mãi này?</h3>
        <h4 class="text-center">
           Khuyến mãi: @Html.DisplayFor(model => model.TenChuongTrinh)
        </h4>
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            <div class="d-flex justify-content-between">
                <input type="submit" value="Xóa" class="btn btn-danger" />
                @Html.ActionLink("Quay lại", "Index", null, new { @class = "btn btn-secondary", style = "color: white !important;" })
            </div>
        }
    </div>
</div>

BookStoreOnline/Areas/Admin/Views/Promotion/Edit.cshtml
@model BookStoreOnline.Models.KHUYENMAI

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="card-body">
    <h2>Chỉnh sửa mã giảm giá</h2>
</div>
@using (Html.BeginForm("Edit", "Promotion", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="mb-3">
            <label for="TenChuongTrinh" class="form-label">Tên chương trình</label>
            @Html.EditorFor(model => model.TenChuongTrinh, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TenChuongTrinh, "", new { @class = "text-danger" })
        </div>

        <div class="mb-3">
            <label for="MaKM" class="form-label">Mã khuyến mãi</label>
            @Html.EditorFor(model => model.MaKM, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.MaKM, "", new { @class = "text-danger" })
        </div>

        <div class="mb-3">
            <label for="MoTa" class="form-label">Mô tả</label>
            @Html.EditorFor(model => model.MoTa, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.MoTa, "", new { @class = "text-danger" })
        </div>

        <div class="mb-3">
            <label for="NgayTao" class="form-label">Ngày tạo</label>
            @Html.EditorFor(model => model.NgayTao, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.NgayTao, "", new { @class = "text-danger" })
        </div>

        <div class="mb-3">
            <label for="NgayBatDau" class="form-label">Ngày bắt đầu</label>
            @Html.EditorFor(model => model.NgayBatDau, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.NgayBatDau, "", new { @class = "text-danger" })
        </div>

        <div class="mb-3">
            <label for="NgayKetThuc" class="form-label">Ngày kết thúc</label>
            @Html.EditorFor(model => model.NgayKetThuc, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.NgayKetThuc, "", new { @class = "text-danger" })
        </div>

        <div class="mb-3">
            <label for="SoTienKM" class="form-label">Số tiền khuyến mãi</label>
            @Html.EditorFor(model => model.SoTienKM, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.SoTienKM, "", new { @class = "text-danger" })
        </div>

        <div class="mb-3">
            <label for="SoTienMuaHangToiThieu" class="form-label">Số tiền mua hàng tối thiểu</label>
            @Html.EditorFor(model => model.SoTienMuaHangToiThieu, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.SoTienMuaHangToiThieu, "", new { @class = "text-danger" })
        </div>

        <div class="mb-3">
            <label for="SoLanDung" class="form-label">Số lần dùng</label>
            @Html.EditorFor(model => model.SoLanDung, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.SoLanDung, "", new { @class = "text-danger" })
        </div>

        <div class="mb-3">
            <label for="KichHoat" class="form-label">Kích hoạt</label>
            <div class="form-check">
                @Html.EditorFor(model => model.KichHoat, new { htmlAttributes = new { @class = "form-check-input" } })
                @Html.ValidationMessageFor(model => model.KichHoat, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="d-flex justify-content-between align-items-center">
            @Html.ActionLink("Quay lại", "Index", null, new { @class = "btn btn-secondary", style = "color: white !important;" })
            <button type="submit" class="btn btn-primary" style="color: white !important;">Lưu thay đổi</button>
        </div>
    </div>
}

BookStoreOnline/Areas/Admin/Views/Promotion/Index.cshtml
@model IEnumerable<BookStoreOnline.Models.KHUYENMAI>
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
<div class="card-body">
    <h2>Các mã khuyến mãi</h2>
</div>
<div class="text-right">
    <button type="button" class="btn btn-primary" onclick="location.href='/Admin/Promotion/Create';">Thêm khuyến mãi mới</button>
</div>
<div class="card-body">
    <div class="table-responsive">
        <table class="table table-striped">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.TenChuongTrinh)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.MaKM)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.MoTa)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.NgayTao)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.NgayBatDau)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.NgayKetThuc)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.SoTienKM)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.SoTienMuaHangToiThieu)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.SoLanDung)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.KichHoat)
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.TenChuongTrinh)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.MaKM)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.MoTa)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.NgayTao)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.NgayBatDau)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.NgayKetThuc)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.SoTienKM)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.SoTienMuaHangToiThieu)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.SoLanDung)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.KichHoat)
                    </td>
                    <td>
                        <div style="display: flex; justify-content: flex-end;">
                            <a href="@Url.Action("Edit", new { id = item.ID})" class="btn btn-sm btn-warning">Chỉnh sửa</a>
                            <a href="@Url.Action("Delete", new { id = item.ID })" class="btn btn-sm btn-danger">Xóa</a>
                        </div>
                    </td>
                </tr>
            }

        </table>
    </div>
</div>